INSERT INTO hackathon.parametro (id,version,descricao,sigla,valor) VALUES (1,0,'URL para chegar a página de Biografia de deputado(a)','url_biografia_deputado','http://www2.camara.leg.br/deputados/pesquisa/layouts_deputados_biografia?pk=');
INSERT INTO hackathon.parametro (id,version,descricao,sigla,valor) VALUES (2,0,'URL do servico que retorna o XML com todos os deputados atuais','url_listagem_deputados','http://www.camara.gov.br/SitCamaraWS/Deputados.asmx/ObterDeputados');
INSERT INTO hackathon.parametro (id,version,descricao,sigla,valor) VALUES (3,0,'URL do serviço que retorna o XML com Proposições','url_listagem_proposicoes','http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoes?numero= &datApresentacaoIni= &datApresentacaoFim= &autor= &parteNomeAutor= &siglaPartidoAutor= &siglaUFAutor= &generoAutor= &codEstado= &codOrgaoEstado= &emTramitacao= &sigla=${sigla}&ano=${ano}');
INSERT INTO hackathon.parametro (id,version,descricao,sigla,valor) VALUES (4,0,'URL do serviço que retorna o XML com os tipos de Proposições','url_listagem_tipos_proposicoes','http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarSiglasTipoProposicao');
INSERT INTO hackathon.parametro (id,version,descricao,sigla,valor) VALUES (5,0,'URL do serviço que retorna o XML com as votações de uma Proposição','url_votacoes_proposicoes','http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ObterVotacaoProposicao?tipo=${tipo}&numero=${numero}&ano=${ano}');
INSERT INTO hackathon.parametro (id,version,descricao,sigla,valor) VALUES (6,0,'URL do servico que retorna o XML as frequencias de todos os deputados em determindado Dia','url_frequecias_dia','http://www.camara.gov.br/SitCamaraWS/sessoesreunioes.asmx/ListarPresencasDia?numLegislatura=&numMatriculaParlamentar=&siglaPartido=&siglaUF=&data=${data}');
INSERT INTO hackathon.parametro (id,version,descricao,sigla,valor) VALUES (7,0,'URL que recupera o XML com os gastos Atuais da Câmara dos Deputados', 'url_gastos', 'http://www.camara.gov.br/cotas/AnoAtual.zip');


