-- Em produção na pasta "bin" (ou similar do SA)
-- Parâmetros
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL para chegar a página de Biografia de deputado(a)','url_biografia_deputado','http://www2.camara.leg.br/deputados/pesquisa/layouts_deputados_biografia?pk=');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do servico que retorna o XML com todos os deputados atuais','url_listagem_deputados','http://www.camara.gov.br/SitCamaraWS/Deputados.asmx/ObterDeputados');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do serviço que retorna o XML com Proposições','url_listagem_proposicoes','http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoes?numero=&datApresentacaoIni=&datApresentacaoFim=&autor=&parteNomeAutor=&siglaPartidoAutor=&siglaUFAutor=&generoAutor=&codEstado=&codOrgaoEstado=&emTramitacao=&sigla=${sigla}&ano=${ano}');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do serviço que retorna o XML com os tipos de Proposições','url_listagem_tipos_proposicoes','http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ListarSiglasTipoProposicao');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do serviço que retorna o XML com as votações de uma Proposição','url_votacoes_proposicoes','http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx/ObterVotacaoProposicao?tipo=${tipo}&numero=${numero}&ano=${ano}');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do servico que retorna o XML as frequencias de todos os deputados em determindado Dia','url_frequecias_dia','http://www.camara.gov.br/SitCamaraWS/sessoesreunioes.asmx/ListarPresencasDia?numLegislatura=&numMatriculaParlamentar=&siglaPartido=&siglaUF=&data=${data}');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL que recupera o XML com os gastos Atuais da Câmara dos Deputados', 'url_gastos', 'http://www.camara.gov.br/cotas/AnoAtual.zip');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do serviço que retorna o XML com dos discursos dos Deputados em certo dia', 'url_discursos', 'http://www.camara.gov.br/sitcamaraws/SessoesReunioes.asmx/ListarDiscursosPlenario?codigoSessao=&parteNomeParlamentar=&siglaPartido=&siglaUF=&dataIni=${data}&dataFim=${data}');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do site da Camara com os discursos de certo Deputado em certo dia', 'url_discurso_deputado_dia', 'http://www.camara.gov.br/internet/sitaqweb/TextoHTML.asp?etapa=${etapa}&nuSessao=${nuSessao}&nuQuarto=${nuQuarto}&nuOrador=${nuOrador}&nuInsercao=${nuInsercao}&dtHorarioQuarto=${horario}&sgFaseSessao=${cdFaseSessao}&Data=${data}&txApelido=${nomeParlamentar}');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do site da Camara com Informações Gerais dos discursos em certo dia', 'url_formacoes_discursos_dia', 'http://www.camara.gov.br/internet/sitaqweb/discursodireto.asp?nuSessao=${nuSessao}');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do site da Camara com Informações sobre os Gastos de certo Deputado', 'url_gastos_site', 'http://www.camara.gov.br/cota-parlamentar/consulta-cota-parlamentar?ideDeputado=');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do site da Camara com Informações sobre os Gastos de certo Deputado em Certo mês', 'url_gastos_site2', 'http://www.camara.gov.br/cota-parlamentar/cota-sumarizado?nuDeputadoId=${nuDeputadoId}&mesAnoConsulta=${mesAno}');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do site da Camara com Informações de uma Proposição', 'url_proposicao_site', 'http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao=');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL para obter URL curta do Google', 'url_shorturl', 'https://www.googleapis.com/urlshortener/v1/url');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do site da Camara com relatório de frequencia de Deputado', 'url_frequencia_site', 'http://www.camara.leg.br/internet/deputado/RelPresencaPlenario.asp?nuLegislatura=54&nuMatricula=${matricula}&dtInicio=${dtinicio}&dtFim=${dtfim}');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do site da Camara a foto Deputado', 'url_foto_deputado', 'http://www.camara.gov.br/internet/deputado/bandep/');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'URL do servico que retorna o XML os partidos', 'url_listagem_partidos', 'http://www.camara.gov.br/SitCamaraWS/Deputados.asmx/ObterPartidosCD');
INSERT INTO parametro (version,descricao,sigla,valor) VALUES (0,'Diretório onde são armazenadas as miniaturas das imagens dos deputados.', 'dir_miniaturas', '/var/lib/tomcat7/shared/prisma-camara/tmp/');

-- Indices
CREATE INDEX idx_despesa ON despesa(data_emissao,deputado_id,txt_numero);
CREATE INDEX idx_hash ON post_nao_enviado(hash,pendente);
CREATE INDEX idx_urlonga ON url_curta(url_longa);